# Generated by Django 4.1.3 on 2022-11-23 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El formato del teléfono debe ser: '9998888777', sin código de país. De 8-14 dígitos permitidos. Puede agregar más telefonos seperados por coma.", regex='^\\d{8,14}((,\\d{8,14})?)*$')], verbose_name='Teléfono Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('domicilio', models.TextField(verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mascotas', models.PositiveSmallIntegerField(verbose_name='Numero de mascotas')),
                ('razones', models.TextField(verbose_name='Razones')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
