# Generated by Django 4.1.3 on 2022-11-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sexo', models.PositiveSmallIntegerField(verbose_name='Sexo')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('fecha_rescate', models.DateField(verbose_name='Fecha de rescate')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('vacuna', models.ManyToManyField(to='mascota.vacuna')),
            ],
        ),
    ]
